version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_NAME=weather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  eurekaserver:
    image: eurekaserver
    ports:
      - "8761:8761"
  weatherservice:
    image: weatherservice
    ports:
      - "8081:8081"
    depends_on:
      - eurekaserver
      - postgres
  currencyservice:
    image: currencyservice
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver
      - postgres
  predict:
    image: predictservice
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
      - weatherservice
      - currencyservice
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
