global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'weatherservice_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['weatherservice:8081']
  - job_name: 'currencyservice_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['currencyservice:8082']
  - job_name: 'predictservice_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['predictservice:8080']