version: "3"
services:
  eurekaserver:
    image: vtal9/eurekaserver:latest
    ports:
      - "8761:8761"

  weatherservice:
    image: vtal9/weatherservice:latest
    ports:
      - "8081:8081"
    depends_on:
      - eurekaserver
  currencyservice:
    image: vtal9/currencyservice:latest
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver
  predict:
    image: vtal9/predictservice:latest
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
      - weatherservice
      - currencyservice
