---
- name: servicesplaybook
  hosts: services
  become: yes

  tasks:
    - name: show dir
      command: ls
      register: output

    - debug:
        var: output

    - name: build weatherservice image
      command: docker build -t '{{ images_prefix }}/{{ weather_service_image_name }}' "{{ deploy_path }}/WeatherCurrencyPredictService/WeatherService"

    - name: build currency service image
      command: docker build -t '{{ images_prefix }}/{{ currency_service_image_name }}' "{{ deploy_path }}/WeatherCurrencyPredictService/CurrecyService"

    - name: build predict service image
      command: docker build -t '{{ images_prefix }}/{{ predict_service_image_name }}' "{{ deploy_path }}/WeatherCurrencyPredictService/PredictService"

    - name: build eureka server image
      command: docker build -t '{{ images_prefix }}/{{ eureka_image_name }}' "{{ deploy_path }}/WeatherCurrencyPredictService/EurikaServer"

    - name: create docker-compose file
      template:
        src: "{{ deploy_path }}/WeatherCurrencyPredictService/ansible/templates/docker-compose.yml.j2"
        dest: "{{ deploy_path }}/docker-compose.yml"

    - name: start services with docker-compose
      docker_compose:
        project_src: "{{ deploy_path }}"